### PR TITLE
Minor updates to manuscript

### PR DESCRIPTION
**Pull request by jchodera**
- Adjusted figure widths
- updated Fig 1 caption
- cleaned up Introduction

### CODE REVIEW

**Comment by jchodera** [comment]
One of the figures---I think `acoustic-vs-tips.pdf`---is consistently crashing my machine!

**Comment by jchodera** [comment]
I think the problem is that `acoustic-vs-tips.pdf` contains all of the bootstrapped samples plotted as lines.  Can we plot only every 10th or 50th bootstrapped sample?  That should reduce the figure complexity a huge amount.

The other solution would be to rasterize it at 300 dpi.

**Comment by sonyahanson** [comment]
I don't have any problems with this figure, will make the figure smaller though, and see if that helps.

-> Would be nice to still get a draft of this to Sean Ekins ~ this week, for which Monday/Tuesday, is probably still passable.

What else do you think needs to be added changed/added, here? There are some obvious things, but your input would be valuable for second half of results and the whole discussion, which I'm not sure you've looked at yet.

**Comment by jchodera** [comment]
> I don't have any problems with this figure, will make the figure smaller though, and see if that helps.

I don't think it's the size---just the number of bootstrap iterates that are drawn.  Only plotting every 10th one would probably be sufficient to fix!

> What else do you think needs to be added changed/added, here? There are some obvious things, but your input would be valuable for second half of results and the whole discussion, which I'm not sure you've looked at yet.

I haven't yet!  Can I take a pass while on the plane and check things in late tonight?

**Comment by sonyahanson** [comment]
That would be great if it's possible! Safe travels!

**Comment by jchodera** [comment]
Didn't get as far through this as I had hoped; let me spend one more hour finishing my changes.

**Comment by jchodera** [comment]
Many many apologies for taking so long with this.  Nearly done with a complete pass--will check in tonight.  Most pressing issue is to fix `acoustic-vs-tips.pdf`---I'll create a separate issue.

**Comment by jchodera** [comment]
Sorry, still working on this.

**Comment by jchodera** [comment]
OK, I'm done for now.  Back to you!

We should probably send this by Sean Ekins for some feedback at this stage.

Again, really sorry to have delayed things so long.  This week was brutal and somehow at a supercomputing center with no internet access.

**Comment by jchodera** [comment]
(Ready to merge!)

**Comment by sonyahanson** [comment]
woohoo!

**Pull request merged**
