### PR TITLE
Addressing Reviewer Comments

### PR DESCRIPTION
**Pull request by sonyahanson**
Addressing reviewer comments.

### CODE REVIEW

**Comment by jchodera** [comment]
Great!  Merge when ready.

**Comment by jchodera** [comment]
Actually, did we mix up the HTML slides vs non-slides?

**Comment by jchodera** [comment]
To get the HTML to render, we may want to include a link that prepends `http://htmlpreview.github.io/?` to the raw file contents. 

For example, here is the link to render your PR (from your repo, not the `choderalab` repo):
http://htmlpreview.github.io/?https://raw.githubusercontent.com/sonyahanson/dispensing-errors-manuscript/master/notebooks/echo-vs-tips.slides.html

Looks like that is the HTML rendering of the whole thing, rather than reveal.js slides.

**Comment by jchodera** [comment]
Scratch that.  They are rendering correctly, but everything is rendered to one slide.  So we may want to delete that.

The non-slide version is rendering fine:
http://htmlpreview.github.io/?https://raw.githubusercontent.com/sonyahanson/dispensing-errors-manuscript/master/notebooks/echo-vs-tips.html

**Comment by jchodera** [comment]
Where are we at with this?  Are we all set to bounce this to Sean for approval?

**Comment by sonyahanson** [comment]
I'm done with everything I wanted to do. Figures have been changed, everything to produce them is in the 'echo-vs-tips-extras.ipynb' ipython notebook, and they have been incorporated in the tex file, and captions changed slightly.

Merge when ready, or let me know if there are any changes that need to be made.

**Comment by jchodera** [comment]
@sonyahanson: Is https://github.com/choderalab/dispensing-errors-manuscript/issues/50 completely addressed?  If so, can you merge this and bounce a copy to Sean to review, calling out what has changed?

**Comment by sonyahanson** [comment]
Will check into the pKi vs. pIC50 thing, and then email the pdf to Sean.

This is what the new figures look like in the manuscript (for expediency):

manu

**Comment by jchodera** [comment]
Looks great!  I like the addition of subcaptions for 8a/8b.

**Comment by sonyahanson** [comment]
Done and Done.

**Comment by sonyahanson** [comment]
If you wanna merge this, I won't be able to do anything again til ~10:30pm. I can make another pull request to finish making this change to both (all four?) ipynbs.

**Comment by sonyahanson** [comment]
Oh and then I need to remake the html too.

**Comment by jchodera** [comment]
Thanks!  Go ahead and do the other things in a separate PR!

**Pull request merged**
