### PR TITLE
Working through results section - figs now added.

### PR DESCRIPTION
**Pull request by sonyahanson**
w007

### CODE REVIEW

**Comment by jchodera** [comment]
The figures look great, but I'm still surprised at the very small bias effect.  Is it hard for you to regenerate these figures once we correct the issues with the IPython notebook that caused the bias effect to be small now?

**Comment by sonyahanson** [comment]
The figures are taken directly from the newest ipython notebook, concerning which there are certainly remaining issues, but they are documented here. Will be easy to change these figures accordingly.

**Comment by jchodera** [comment]
Which is "the newest ipython notebook"?  Is that `New_format_with_slider.ipynb`, `New_Template.ipynb`, or `Serial Dilution Accuracy.ipynb`?

**Comment by sonyahanson** [comment]
Up for merging this, and opening new pull request for the rest to avoid a mess.

**Comment by jchodera** [comment]
Go for it!  Feel free to merge these things whenever.  Thank you for using
PRs---makes it much easier to follow along!

**Pull request merged**
