### PR TITLE
made last couple EKins changes

### PR DESCRIPTION
**Pull request by sonyahanson**
made last couple Ekins changes

### CODE REVIEW

**Comment by jchodera** [comment]
Danke!

**Comment by sonyahanson** [comment]
This might be worth mentioning to Sean, since it was wrong in the version he saw:
change

**Comment by sonyahanson** [comment]
Read through the discussion. No changes here!

**Comment by jchodera** [comment]
Please do chime in on the Ekins email about the RMSD thing!

**Pull request merged**
