### PR TITLE
Fixed -dilute 2 ul transfer- and -IC50 vs Ki- in ipynb - now named `echo-vs-tips.ipynb`

### PR DESCRIPTION
**Pull request by sonyahanson**
Fixed 'dilute 2 ul transfer' (#24) and 'IC50 vs Ki' (#17) in ipynb - now named `echo-vs-tips.ipynb`. 

Didn't delete anything yet, just to make things super confusing.

### CODE REVIEW

**Comment by sonyahanson** [comment]
One question on the IC50 to Ki transfer, in my cell 59, first cell of section five, is this still correct?

<pre>
echo_pIC50_err = (echo_pIC50_CV*np.abs(pKis))
genesis_pIC50_err = (genesis_pIC50_CV*np.abs(pKis))
</pre>

**Comment by jchodera** [comment]
> One question on the IC50 to Ki transfer, in my cell 59, first cell of section five, is this still correct?

Looks correct to me!

**Comment by sonyahanson** [comment]
Just to be a bit more explicit, I am not clear whether it should be as above or

<pre>
echo_pIC50_err = (echo_pIC50_CV*np.abs(pIC50s))
genesis_pIC50_err = (genesis_pIC50_CV*np.abs(pIC50s))
</pre>

**Comment by sonyahanson** [comment]
Kept the question above the same as is. Everything seems fine. As far as I'm concerned these notebooks are pretty complete.

**Comment by sonyahanson** [comment]
Adding the `echo-vs-tips-extras.ipynb` was my solution to (#20) it has the sliders in at the end. This notebook also makes the figures! 

Briefly tried making the figures with a separate python script, but realized I had been depending on the default figure sizes for ipython notebook, and didn't feel like it made sense to make new problems for myself.

**Pull request merged**
