### PR TITLE
Working through results section - added new dilution effect figure and starting explaining math

### PR DESCRIPTION
**Pull request by sonyahanson**

### CODE REVIEW

**Comment by jchodera** [comment]
Figure looks great!

**Comment by sonyahanson** [comment]
Added some more text for the first few sections of results. Sections on mixing, modeling enzyme reaction, and plate-reader error still need to be filled in.

I added two references on mixing to the zotero library (one on 96-well one on 384-well mixing), but haven't put them into the bib file yet. I couldn't find the poster that I think we've been referencing so far that talks about the importance of mixing ~11 times?

Other refs to be added: patents, blogs, bootstrapping, inaccuracy and imprecision data, table refs from ekins, reproducibility initiative ref could be added to discussion. Also their is still some stuff to fill in at the end of the Intro that I haven't gotten to yet.

I think I'm going to switch to fixing up the ipython notebook and making the figure generating scripts (and make the last figure that currently just has a placeholder), so it'd be great if you could read through what's in here so far and make edits, and add in anything mentioned above that you have time for @jchodera .

**Comment by jchodera** [comment]
Thanks!

I've just forwarded some other potentially useful references on mixing, including some posters.  Not sure if you already have all those.

**Comment by jchodera** [comment]
> I think I'm going to switch to fixing up the ipython notebook and making the figure generating scripts (and make the last figure that currently just has a placeholder), so it'd be great if you could read through what's in here so far and make edits, and add in anything mentioned above that you have time for @jchodera .

OK!  How about you merge this and then I take a pass through?

**Comment by sonyahanson** [comment]
Done.

**Pull request merged**
