### PR TITLE
More SMH changes - first fixed Fig 5

### PR DESCRIPTION
**Pull request by sonyahanson**
More SMH changes: fixed Fig 5.

### CODE REVIEW

**Comment by sonyahanson** [comment]
Fixed a few things I thought might be wrong. Snapshots:

bufferstock

indended

**Comment by sonyahanson** [comment]
Added in the equations for tip-based and direct dispensing. They might need some tweeking.

**Comment by sonyahanson** [comment]
Read through the Intro up to Modeling an enzymatic assay, and didn't find anything notable to fix. Some parts are a bit hard to get through, but nothing glaring, or that I could think of how to fix.

**Comment by sonyahanson** [comment]
Thought about the 'Modeling plate reader measurement' section. Literally was about to delete the whole thing. I'm not sure it deserves it's own section in this particular paper, and I'm not sure what section it could be folded into either... 'inherent noise in any fluorescence measurement' is already mentioned in the Intro.

**Comment by jchodera** [comment]
> Thought about the 'Modeling plate reader measurement' section. Literally was about to delete the whole thing. I'm not sure it deserves it's own section in this particular paper, and I'm not sure what section it could be folded into either... 'inherent noise in any fluorescence measurement' is already mentioned in the Intro.

I think we should just delete the whole section and note that we are neglecting reader noise and the minimum detectable signal in either "Fitting the assay readout" (at the beginning) or "Modeling an enzymatic reaction" at the end.

Alternatively, we don't really have an overview section that states how we put all of these things together.  We might instead turn the plate reader section into a "Putting it all together into an assay model" section that describes the overall flow of each experimental model---even just in bullet points---where we assume the readout is just proportional to the relative enzyme velocity or product accumulation.

**Comment by jchodera** [comment]
I am ready to take this over and continue on whenever you say it's OK to merge!

**Comment by sonyahanson** [comment]
okay to merge

**Pull request merged**
