### PR TITLE
Updated figures in manuscript according to latest in `extras.ipynb`

### PR DESCRIPTION
**Pull request by sonyahanson**
Updated figures in manuscript according to latest figures from `echo-vs-tips-extras.ipynb`

### CODE REVIEW

**Comment by sonyahanson** [comment]
New zotero-generated .bib file mentioned in (#28) is now here!

**Comment by sonyahanson** [comment]
Something strange going on here with "In the Pipeline" URL:

refs_oops

**Comment by jchodera** [comment]
URL wrapping is not very intelligent.  I think the line splitting rules allow splitting on hyphens but not underscores:
http://tex.stackexchange.com/questions/100391/how-to-wrap-a-word-in-line-without-hyphen

**Comment by jchodera** [comment]
See here for info on adding `patent` block to `bst`:
https://github.com/scoppen/Patent-Template-for-LaTeX/blob/master/patent.bst#L544-L553

**Comment by sonyahanson** [comment]
Feel free to take a pass through this @jchodera. There's a few outstanding things still (some refs, adding plate reader error and D300 plug to discussion), but I won't be doing anything else on this tonight.

**Comment by jchodera** [comment]
Thanks!  Can I merge this and open my own PR?

**Comment by sonyahanson** [comment]
Go for it!

**Comment by jchodera** [comment]
Did you have any input on the blue text that was repetitive?   I think we want to cut one of them---any preference?

**Comment by sonyahanson** [comment]
I honestly thought it was fine the way it was... Maybe a few repetitive words/clauses could be cut from the first one.

**Pull request merged**
