### PR TITLE
Added new format ipython notebook!

### PR DESCRIPTION
**Pull request by sonyahanson**
This is mostly complete, some things to note:

There are a few funky things that don't compare directly to the 'Serial_Dilution_Accuracy' notebook. I expect I have some variable overlaps or something. Namely the things that don't match up are the **pIC50 bias for the echo model** and the **CV for the DILUTE_ROBOT** model.

Also, the IC50 data seems to be backwards again for the DILUTE_ROBOT model, I think somehow I did this before, and you fixed it @jchodera, but I'm not sure you said explicitly how/what the problem was.

Note that the `robot_dispense` function is not included now.

Some wishlist items if there's time (but we should really probably stop playing with this):
- Add D300 bit
- Add detection limit for spectrometer
- Change slider widgets to `ipython.html` from `ipywidget` (maybe then it will show in the github preview, too?)
- Make some things (especially plotting) into functions

### CODE REVIEW

**Comment by jchodera** [comment]
> Also, the IC50 data seems to be backwards again for the DILUTE_ROBOT model, I think somehow I did this before, and you fixed it @jchodera, but I'm not sure you said explicitly how/what the problem was.

I think you had defined a concentration series for one experiment and then accidentally reused it for a different experiment in which the concentrations were supposed to go the other way.  It was definitely a bug, so it would be good to carefully go through and fix things like this since they could lead to incorrect results.

**Comment by jchodera** [comment]
Previously, there was also some confusion between the stated (intended) concentrations and the true concentrations.  We intended to plot measurements as a function of the stated concentrations, I believe.  Not sure if that issue pops up here too.

**Comment by jchodera** [comment]
> Change slider widgets to ipython.html from ipywidget (maybe then it will show in the github preview, too?)

This would be super useful, since it would mean the user doesn't need to install new things to get these to work.

**Comment by jchodera** [comment]
This new notebook is gorgeous, by the way!

**Comment by jchodera** [comment]
Cell 31 looks wrong to me.  The pIC50 CV as a function of pKi is way too small.  Even just eyeballing Cell 26, we see the CV should be ~1%, but Cell 31 shows it as << 0.1%, maybe even << 0.01%.

**Comment by jchodera** [comment]
Cell 28 has a bug.  You have

```
[actual_volumes, actual_concentrations] = ROBOT_dilution_series(Vinitial, C0, Vtransfer, Vbuffer, ndilutions, tecan_genesis_pipetting_model)
        activities = np.zeros([ndilutions], np.float64)
        for i in range(ndilutions):
            activities[i] = competitive_inhibition(substrate_concentration, assay_compound_concentrations[i], enzyme_concentration, true_Ki, Km)
```

The `competitive_inhibition()` call should take `actual_concentrations[i]` as an argument, not `assay_compound_concentrations[i]`.  

We should take a careful pass through and see if we've accidentally mixed up the two elsewhere as well.

**Comment by sonyahanson** [comment]
Thanks! This helps a ton! Should we fix these problems before merging?

**Comment by jchodera** [comment]
Would be great to, but it may be easier to just merge and have me create a PR tomorrow if you want me to take a pass through. 

Alternatively, I can just read through and make some line comments if you would prefer!

**Comment by sonyahanson** [comment]
Working on these changes now, has been pretty straightforward, will commit soonish hopefully.

**Comment by sonyahanson** [comment]
Made all the appropriate changes of assay_compound_concentrations[i]  to  actual_concentrations[i]. The comment on cell 31 being too small was fixed with this.

Also found that ideal_concentrations was defined twice, once for the echo and once for tips. Have now changed the echo one to echo_ideal_concentrations. This seems to have fixed the wrong direction for the IC50 curve for the DILUTE_ROBOT model. It is mostly fixed the pIC50 bias for the echo model, though this is now slightly closer to zero than for the 'Serial_Dilution_Accuracy' notebook. The CV and bias for DILUTE_ROBOT is now similar to the 'Serial_Dilution_Accuracy' notebook, however the bias for the pIC50 is now lower than before, which does effect our final chart. 

Help debugging this last bit much appreicated.

**Comment by jchodera** [comment]
Apologies that I don't have time to look at this in great detail until my flight tomorrow, but [here is a nice tutorial on using `scipy.optimize.curve_fit` to fit models to data](http://www2.mpia-hd.mpg.de/~robitaille/PY4SCI_SS_2014/_static/15.%20Fitting%20models%20to%20data.html)!

**Comment by jchodera** [comment]
I may be confused about where the data we're using came from.  Is it from [this patent](http://www.google.com/patents/US7718653)?  The section on assay (A)

```
EXAMPLE 13 Biological Assays
A) In vitro EphB4 Enzyme Assay
```

says there was 0.25 ng of EphB4 in 10 uL assay buffer, which is an enzyme concentration of (MW 76.8 kDa), which gives (0.25e-9 g) / (76.8e3 g/mol) / (10e-6 L) = 32.5 nM kinase.  The notebook says 4 uM ATP, but 6 uM enzyme concentration.  Not sure if I misread that or took a wild guess or something.

**Comment by sonyahanson** [comment]
As far as I can tell the data is from that patent. Though there are a few extra compounds that start with W in the Ekins paper.

I'm going to go ahead and make a new issue about changing the actual values of the assay to correspond to these.

**Comment by sonyahanson** [comment]
I've copied your `scipy.optimize.curve_fit` comment to the appropriate issue.

I think I'm going to go ahead and merge this, as I feel like the notebook is currently in an okay place, with a few very specific things we need to deal with.

And I think I ought to return to editing the actual paper and figures.

Feel free to edit the notebook in the mean time.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
